const DEFAULT_EVIDENCE_FOLDER = "elite-program-evidence";

export const EVIDENCE_KINDS = ["opening", "closing", "payment"] as const;
export type EvidenceKind = (typeof EVIDENCE_KINDS)[number];

export const ALLOWED_EVIDENCE_MIME_TYPES = [
  "image/jpeg",
  "image/png",
  "image/webp",
] as const;

export const ALLOWED_EVIDENCE_EXTENSIONS = ["jpg", "jpeg", "png", "webp"] as const;
export const MAX_EVIDENCE_FILE_SIZE_BYTES = 5 * 1024 * 1024;

export function normalizeEvidenceKind(value: unknown): EvidenceKind {
  const requestedKind = String(value || "opening").trim().toLowerCase();
  return EVIDENCE_KINDS.includes(requestedKind as EvidenceKind)
    ? (requestedKind as EvidenceKind)
    : "opening";
}

export function getCloudinaryEvidenceConfig() {
  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  const apiKey = process.env.CLOUDINARY_API_KEY;
  const apiSecret = process.env.CLOUDINARY_API_SECRET;
  const folder = (
    process.env.CLOUDINARY_EVIDENCE_FOLDER || DEFAULT_EVIDENCE_FOLDER
  )
    .trim()
    .replace(/^\/+|\/+$/g, "");

  if (!cloudName || !apiKey || !apiSecret) {
    throw new Error("Cloudinary is not configured");
  }

  return { cloudName, apiKey, apiSecret, folder };
}

export function getEvidenceFolder() {
  return (process.env.CLOUDINARY_EVIDENCE_FOLDER || DEFAULT_EVIDENCE_FOLDER)
    .trim()
    .replace(/^\/+|\/+$/g, "");
}

export function getSafeEvidenceUserPrefix(userId: number | string) {
  return `u_${String(userId).replace(/[^a-zA-Z0-9_-]/g, "_").slice(0, 64)}`;
}

export function sanitizeEvidenceDisplayName(name: unknown) {
  const safeName = String(name || "evidence-image")
    .replace(/[\\/\u0000-\u001f\u007f]/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 120);

  return safeName || "evidence-image";
}

export function getEvidenceExtensionFromMime(mimeType: string) {
  if (mimeType === "image/jpeg") return "jpg";
  if (mimeType === "image/png") return "png";
  if (mimeType === "image/webp") return "webp";
  return null;
}

export function detectEvidenceMimeFromBytes(bytes: Uint8Array) {
  if (bytes.length >= 3 && bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) {
    return "image/jpeg";
  }

  if (
    bytes.length >= 8 &&
    bytes[0] === 0x89 &&
    bytes[1] === 0x50 &&
    bytes[2] === 0x4e &&
    bytes[3] === 0x47 &&
    bytes[4] === 0x0d &&
    bytes[5] === 0x0a &&
    bytes[6] === 0x1a &&
    bytes[7] === 0x0a
  ) {
    return "image/png";
  }

  if (
    bytes.length >= 12 &&
    bytes[0] === 0x52 &&
    bytes[1] === 0x49 &&
    bytes[2] === 0x46 &&
    bytes[3] === 0x46 &&
    bytes[8] === 0x57 &&
    bytes[9] === 0x45 &&
    bytes[10] === 0x42 &&
    bytes[11] === 0x50
  ) {
    return "image/webp";
  }

  return null;
}

export function assertAllowedEvidenceFileMetadata(file: File) {
  if (!ALLOWED_EVIDENCE_MIME_TYPES.includes(file.type as (typeof ALLOWED_EVIDENCE_MIME_TYPES)[number])) {
    throw new Error("Only JPG, PNG, or WEBP evidence images are allowed.");
  }

  if (file.size <= 0) {
    throw new Error("Evidence image is empty.");
  }

  if (file.size > MAX_EVIDENCE_FILE_SIZE_BYTES) {
    throw new Error("Evidence image must be 5 MB or smaller.");
  }
}

export function assertAllowedEvidenceBytes(bytes: Uint8Array, claimedMimeType: string) {
  const detectedMimeType = detectEvidenceMimeFromBytes(bytes);

  if (!detectedMimeType) {
    throw new Error("Invalid evidence image. Only real JPG, PNG, or WEBP files are allowed.");
  }

  if (detectedMimeType !== claimedMimeType) {
    throw new Error("Evidence image type does not match the uploaded file content.");
  }

  return detectedMimeType;
}

export function assertValidEvidenceUrlForUser(
  evidenceUrl: string | null | undefined,
  userId: number | string,
  expectedKind?: EvidenceKind,
) {
  const rawUrl = String(evidenceUrl || "").trim();
  if (!rawUrl) return null;

  let parsedUrl: URL;
  try {
    parsedUrl = new URL(rawUrl);
  } catch {
    throw new Error("Invalid evidence URL.");
  }

  const cloudName = process.env.CLOUDINARY_CLOUD_NAME;
  if (!cloudName) {
    throw new Error("Cloudinary is not configured");
  }

  if (parsedUrl.protocol !== "https:") {
    throw new Error("Evidence URL must use HTTPS.");
  }

  if (parsedUrl.hostname !== "res.cloudinary.com") {
    throw new Error("Evidence URL must be a Cloudinary URL generated by this application.");
  }

  const decodedPath = decodeURIComponent(parsedUrl.pathname);
  const requiredPrefix = `/${cloudName}/image/upload/`;
  if (!decodedPath.startsWith(requiredPrefix)) {
    throw new Error("Evidence URL does not belong to this Cloudinary account.");
  }

  const folder = getEvidenceFolder();
  const safeUserPrefix = getSafeEvidenceUserPrefix(userId);
  const allowedKinds = expectedKind ? [expectedKind] : [...EVIDENCE_KINDS];
  const normalizedPath = decodedPath.replace(/\/+/g, "/");

  const hasExpectedFolder = allowedKinds.some((kind) => {
    const folderMarker = `/${folder}/${kind}/${safeUserPrefix}-`;
    return normalizedPath.includes(folderMarker);
  });

  if (!hasExpectedFolder) {
    throw new Error("Evidence URL was not uploaded by this user for this evidence type.");
  }

  const extension = normalizedPath.split(".").pop()?.toLowerCase() || "";
  if (!ALLOWED_EVIDENCE_EXTENSIONS.includes(extension as (typeof ALLOWED_EVIDENCE_EXTENSIONS)[number])) {
    throw new Error("Evidence URL must point to a JPG, PNG, or WEBP image.");
  }

  return rawUrl;
}
