-- ============================================================
-- MISSING MIGRATION — Bank transfer / manual payment support
-- ============================================================
-- Reconstructed by diffing the production dump (theolddeployedapp.sql)
-- against the current dev schema (application-now.sql). Every other schema
-- difference between the two is already covered by a file in migrations/;
-- this one was never written.
--
-- It backs the admin bank-settings page and the manual-transfer payment flow:
--   src/app/admin/bank-settings/page.tsx
--   src/app/admin/firm-profit-payments/page.tsx
--   src/app/api/mobile/v1/elite/bank-accounts/route.ts
--   src/app/api/mobile/v1/elite/firm-profit-payments/route.ts
--   src/app/api/mobile/v1/elite/firm-profit-payments/[id]/proof/route.ts
--   src/app/api/elite/firm-profit-payment/route.ts
--   src/modules/program/program.service.ts
--
-- Apply with: psql "$DATABASE_URL" -f migrations/bank_transfer_payments.sql
-- Run it AFTER elite_loss_carry_forward.sql. Re-runnable.
-- ============================================================

BEGIN;

-- ------------------------------------------------------------
-- Admin-managed payout destinations
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS firm_bank_accounts (
    id                integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_name      character varying(150) NOT NULL,
    bank_name         character varying(150) NOT NULL,
    iban              character varying(50)  NOT NULL,
    swift_code        character varying(50),
    currency          character varying(3)   NOT NULL DEFAULT 'USD',
    country           character varying(80),
    instructions      text,
    is_active         boolean NOT NULL DEFAULT true,
    created_at        timestamp with time zone NOT NULL DEFAULT now(),
    updated_at        timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT firm_bank_accounts_currency_check
        CHECK (currency ~ '^[A-Z]{3}$')
);

CREATE INDEX IF NOT EXISTS firm_bank_accounts_active_idx
    ON firm_bank_accounts (is_active, updated_at DESC);

-- ------------------------------------------------------------
-- Manual-transfer workflow columns on firm_profit_payments
-- ------------------------------------------------------------
ALTER TABLE firm_profit_payments
    ADD COLUMN IF NOT EXISTS payment_method      character varying(30) NOT NULL DEFAULT 'STRIPE',
    ADD COLUMN IF NOT EXISTS bank_account_id     integer,
    ADD COLUMN IF NOT EXISTS manual_reference    character varying(80),
    ADD COLUMN IF NOT EXISTS transfer_reference  character varying(120),
    ADD COLUMN IF NOT EXISTS proof_url           text,
    ADD COLUMN IF NOT EXISTS proof_name          character varying(255),
    ADD COLUMN IF NOT EXISTS submitted_at        timestamp with time zone,
    ADD COLUMN IF NOT EXISTS reviewed_by         integer,
    ADD COLUMN IF NOT EXISTS reviewed_at         timestamp with time zone,
    ADD COLUMN IF NOT EXISTS review_note         text;

-- Existing rows are all Stripe payments; the DEFAULT above already
-- backfills them to 'STRIPE', so no UPDATE is needed.

-- ------------------------------------------------------------
-- Foreign keys (guarded so this file is re-runnable)
-- ------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'firm_profit_payments_bank_account_id_fkey'
    ) THEN
        ALTER TABLE firm_profit_payments
            ADD CONSTRAINT firm_profit_payments_bank_account_id_fkey
            FOREIGN KEY (bank_account_id)
            REFERENCES firm_bank_accounts(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'firm_profit_payments_reviewed_by_fkey'
    ) THEN
        ALTER TABLE firm_profit_payments
            ADD CONSTRAINT firm_profit_payments_reviewed_by_fkey
            FOREIGN KEY (reviewed_by)
            REFERENCES users(id) ON DELETE SET NULL;
    END IF;
END $$;

-- ------------------------------------------------------------
-- Widen the status CHECK.
-- Production currently allows only:
--   PENDING, CHECKOUT_CREATED, PAID, FAILED, EXPIRED, CANCELLED
-- The manual-transfer flow adds four more states. Without this, the first
-- bank-transfer payment that leaves PENDING raises a check_violation.
-- ------------------------------------------------------------
ALTER TABLE firm_profit_payments
    DROP CONSTRAINT IF EXISTS firm_profit_payments_status_check;

ALTER TABLE firm_profit_payments
    ADD CONSTRAINT firm_profit_payments_status_check
    CHECK (status IN (
        'PENDING', 'CHECKOUT_CREATED', 'AWAITING_TRANSFER', 'PROOF_SUBMITTED',
        'UNDER_REVIEW', 'PAID', 'REJECTED', 'FAILED', 'EXPIRED', 'CANCELLED'
    ));

ALTER TABLE firm_profit_payments
    DROP CONSTRAINT IF EXISTS firm_profit_payments_method_check;

ALTER TABLE firm_profit_payments
    ADD CONSTRAINT firm_profit_payments_method_check
    CHECK (payment_method IN ('STRIPE', 'BANK_TRANSFER', 'CASH', 'OTHER'));

-- ------------------------------------------------------------
-- Indexes
-- ------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS firm_profit_payments_manual_reference_uq
    ON firm_profit_payments (manual_reference)
    WHERE manual_reference IS NOT NULL;

CREATE INDEX IF NOT EXISTS firm_profit_payments_method_status_idx
    ON firm_profit_payments (payment_method, status, created_at DESC);

COMMIT;
